CREATE TABLE CLIENTE(CNPJ NUMERIC(14) NOT NULL, RAZAO_SOCIAL VARCHAR(80), NOME_FANTASIA VARCHAR(80), IE NUMERIC(12), SALDO NUMERIC(8,2),
 SITUACAO VARCHAR(1) NOT NULL, DT_CADASTRO DATETIME, PTSMAISVANTAGEM NUMERIC(8));CREATE TABLE `cliente` (
  `CNPJ` decimal(14,0) NOT NULL,
  `RAZAO_SOCIAL` varchar(80) DEFAULT NULL,
  `NOME_FANTASIA` varchar(80) DEFAULT NULL,
  `IE` decimal(12,0) DEFAULT NULL,
  `SALDO` decimal(8,2) DEFAULT NULL,
  `SITUACAO` varchar(1) NOT NULL,
  `DT_CADASTRO` datetime DEFAULT NULL,
  `PTSMAISVANTAGEM` decimal(8,0) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `item_pedido` (
  `NUM_PEDIDO` int NOT NULL,
  `COD_PRODUTO` int NOT NULL,
  `CFOP` int NOT NULL,
  `QUANT` int NOT NULL,
  `VR_DESC` decimal(9,2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `pedido` (
  `NUM_PEDIDO` int NOT NULL,
  `CNPJ_CLIENTE` decimal(14,0) NOT NULL,
  `CPF_FUNC` decimal(11,0) NOT NULL,
  `DT_EMISSAO` datetime DEFAULT NULL,
  `DT_CARREGA` datetime DEFAULT NULL,
  `DT_ANALISE` datetime DEFAULT NULL,
  `OBS` varchar(80) DEFAULT NULL,
  `TIPO_FRETE` varchar(1) DEFAULT NULL,
  `NUM_NF` int NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `produto` (
  `COD_PRODUTO` int NOT NULL,
  `DESCRICAO` varchar(80) DEFAULT NULL,
  `ATIVO` varchar(1) DEFAULT NULL,
  `NCM_SH` int DEFAULT NULL,
  `CST` int DEFAULT NULL,
  `UNIDADE` int DEFAULT NULL,
  `VR_UNITARIO` decimal(8,2) DEFAULT NULL,
  `ALI_ICMS` decimal(8,2) DEFAULT NULL,
  `ALI_IPI` decimal(8,2) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
